export const assets = {
  bag: require("./bag.png"),
  back: require("./back.png"),
  clock: require("./clock.png"),
  user: require("./user.png"),
  cash: require("./cash.png"),
  apple: require("./apple.png"),
  cheese: require("./cheese.png"),
  corn: require("./corn.png"),
  eggplant: require("./eggplant.png"),
  tomato: require("./tomato.png"),
  carrot: require("./carrot.png"),
  steak: require("./steak.png"),
  avocado: require("./avocado.png"),
  honey: require("./honey.png"),
  pasta: require("./pasta.png"),
  pepper: require("./pepper.png"),
  salt: require("./salt.png"),
  vegan: require("./vegan.png"),
  glutenFree: require("./gluten.png"),
  dairyFree: require("./milk.png"),
  fish: require("./fish.png"),
};
